export default [
  {
    name: 'Afghanistan',
    code: 'AF',
    id: 1,
    phone: 93,
    icon: require('./country_assets/AF.png'),
  },
  {
    name: 'Aland Islands',
    code: 'AX',
    id: 2,
    phone: 358,
    icon: require('./country_assets/AX.png'),
  },
  {
    name: 'Albania',
    code: 'AL',
    id: 3,
    phone: 355,
    icon: require('./country_assets/AL.png'),
  },
  {
    name: 'Algeria',
    code: 'DZ',
    id: 4,
    phone: 213,
    icon: require('./country_assets/DZ.png'),
  },
  {
    name: 'American Samoa',
    code: 'AS',
    id: 5,
    phone: 1684,
    icon: require('./country_assets/AS.png'),
  },
  {
    name: 'Andorra',
    code: 'AD',
    id: 6,
    phone: 376,
    icon: require('./country_assets/AD.png'),
  },
  {
    name: 'Angola',
    code: 'AO',
    id: 7,
    phone: 244,
    icon: require('./country_assets/AO.png'),
  },
  {
    name: 'Anguilla',
    code: 'AI',
    id: 8,
    phone: 1264,
    icon: require('./country_assets/AI.png'),
  },
  {
    name: 'Antarctica',
    code: 'AQ',
    id: 9,
    phone: 672,
    icon: require('./country_assets/AQ.png'),
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    id: 10,
    phone: 1268,
    icon: require('./country_assets/AG.png'),
  },
  {
    name: 'Argentina',
    code: 'AR',
    id: 11,
    phone: 54,
    icon: require('./country_assets/AR.png'),
  },
  {
    name: 'Armenia',
    code: 'AM',
    id: 12,
    phone: 374,
    icon: require('./country_assets/AM.png'),
  },
  {
    name: 'Aruba',
    code: 'AW',
    id: 13,
    phone: 297,
    icon: require('./country_assets/AW.png'),
  },
  {
    name: 'Australia',
    code: 'AU',
    id: 14,
    phone: 61,
    icon: require('./country_assets/AU.png'),
  },
  {
    name: 'Austria',
    code: 'AT',
    id: 15,
    phone: 43,
    icon: require('./country_assets/AT.png'),
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    id: 16,
    phone: 994,
    icon: require('./country_assets/AZ.png'),
  },
  {
    name: 'Bahamas',
    code: 'BS',
    id: 17,
    phone: 1242,
    icon: require('./country_assets/BS.png'),
  },
  {
    name: 'Bahrain',
    code: 'BH',
    id: 18,
    phone: 973,
    icon: require('./country_assets/BH.png'),
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    id: 19,
    phone: 880,
    icon: require('./country_assets/BD.png'),
  },
  {
    name: 'Barbados',
    code: 'BB',
    id: 20,
    phone: 1246,
    icon: require('./country_assets/BB.png'),
  },
  {
    name: 'Belarus',
    code: 'BY',
    id: 21,
    phone: 375,
    icon: require('./country_assets/BY.png'),
  },
  {
    name: 'Belgium',
    code: 'BE',
    id: 22,
    phone: 32,
    icon: require('./country_assets/BE.png'),
  },
  {
    name: 'Belize',
    code: 'BZ',
    id: 23,
    phone: 501,
    icon: require('./country_assets/BZ.png'),
  },
  {
    name: 'Benin',
    code: 'BJ',
    id: 24,
    phone: 229,
    icon: require('./country_assets/BJ.png'),
  },
  {
    name: 'Bermuda',
    code: 'BM',
    id: 25,
    phone: 1441,
    icon: require('./country_assets/BM.png'),
  },
  {
    name: 'Bhutan',
    code: 'BT',
    id: 26,
    phone: 975,
    icon: require('./country_assets/BT.png'),
  },
  {
    name: 'Bolivia',
    code: 'BO',
    id: 27,
    phone: 591,
    icon: require('./country_assets/BO.png'),
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    code: 'BQ',
    id: 28,
    phone: 599,
    icon: require('./country_assets/BQ.png'),
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    id: 29,
    phone: 387,
    icon: require('./country_assets/BA.png'),
  },
  {
    name: 'Botswana',
    code: 'BW',
    id: 30,
    phone: 267,
    icon: require('./country_assets/BW.png'),
  },
  {
    name: 'Bouvet Island',
    code: 'BV',
    id: 31,
    phone: 55,

    icon: require('./country_assets/BV.png'),
  },
  {
    name: 'Brazil',
    code: 'BR',
    id: 32,
    phone: 55,
    icon: require('./country_assets/BR.png'),
  },
  {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    id: 33,
    phone: 246,
    icon: require('./country_assets/IO.png'),
  },
  {
    name: 'Brunei Darussalam',
    code: 'BN',
    id: 34,
    phone: 673,
    icon: require('./country_assets/BN.png'),
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    id: 35,
    phone: 359,
    icon: require('./country_assets/BG.png'),
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    id: 36,
    phone: 226,
    icon: require('./country_assets/BF.png'),
  },
  {
    name: 'Burundi',
    code: 'BI',
    id: 37,
    phone: 257,
    icon: require('./country_assets/BI.png'),
  },
  {
    name: 'Cambodia',
    code: 'KH',
    id: 38,
    phone: 855,
    icon: require('./country_assets/KH.png'),
  },
  {
    name: 'Cameroon',
    code: 'CM',
    id: 39,
    phone: 237,
    icon: require('./country_assets/CM.png'),
  },
  {
    name: 'Canada',
    code: 'CA',
    id: 40,
    phone: 1,
    icon: require('./country_assets/CA.png'),
  },
  {
    name: 'Cape Verde',
    code: 'CV',
    id: 41,
    phone: 238,
    icon: require('./country_assets/CV.png'),
  },
  {
    name: 'Cayman Islands',
    code: 'KY',
    id: 42,
    phone: 1345,
    icon: require('./country_assets/KY.png'),
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    id: 43,
    phone: 236,
    icon: require('./country_assets/CF.png'),
  },
  {
    name: 'Chad',
    code: 'TD',
    id: 44,
    phone: 235,
    icon: require('./country_assets/TD.png'),
  },
  {
    name: 'Chile',
    code: 'CL',
    id: 45,
    phone: 56,
    icon: require('./country_assets/CL.png'),
  },
  {
    name: 'China',
    code: 'CN',
    id: 46,
    phone: 86,
    icon: require('./country_assets/CN.png'),
  },
  {
    name: 'Christmas Island',
    code: 'CX',
    id: 47,
    phone: 61,
    icon: require('./country_assets/CX.png'),
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    id: 48,
    phone: 672,
    icon: require('./country_assets/CC.png'),
  },
  {
    name: 'Colombia',
    code: 'CO',
    id: 49,
    phone: 57,
    icon: require('./country_assets/CO.png'),
  },
  {
    name: 'Comoros',
    code: 'KM',
    id: 50,
    phone: 269,
    icon: require('./country_assets/KM.png'),
  },
  {
    name: 'Congo',
    code: 'CG',
    id: 51,
    phone: 242,
    icon: require('./country_assets/CG.png'),
  },
  {
    name: 'Congo, Democratic Republic of the Congo',
    code: 'CD',
    id: 52,
    phone: 242,
    icon: require('./country_assets/CD.png'),
  },
  {
    name: 'Cook Islands',
    code: 'CK',
    id: 53,
    phone: 682,
    icon: require('./country_assets/CK.png'),
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    id: 54,
    phone: 506,
    icon: require('./country_assets/CR.png'),
  },
  {
    name: "Cote D'Ivoire",
    code: 'CI',
    id: 55,
    phone: 225,
    icon: require('./country_assets/CI.png'),
  },
  {
    name: 'Croatia',
    code: 'HR',
    id: 56,
    phone: 385,
    icon: require('./country_assets/HR.png'),
  },
  {
    name: 'Cuba',
    code: 'CU',
    id: 57,
    phone: 53,
    icon: require('./country_assets/CU.png'),
  },
  {
    name: 'Curacao',
    code: 'CW',
    id: 58,
    phone: 599,
    icon: require('./country_assets/CW.png'),
  },
  {
    name: 'Cyprus',
    code: 'CY',
    id: 59,
    phone: 357,
    icon: require('./country_assets/CY.png'),
  },
  {
    name: 'Czech Republic',
    code: 'CZ',
    id: 60,
    phone: 420,
    icon: require('./country_assets/CZ.png'),
  },
  {
    name: 'Denmark',
    code: 'DK',
    id: 61,
    phone: 45,
    icon: require('./country_assets/DK.png'),
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    id: 62,
    phone: 253,
    icon: require('./country_assets/DJ.png'),
  },
  {
    name: 'Dominica',
    code: 'DM',
    id: 63,
    phone: 1767,
    icon: require('./country_assets/DM.png'),
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    id: 64,
    phone: 1809,
    icon: require('./country_assets/DO.png'),
  },
  {
    name: 'Ecuador',
    code: 'EC',
    id: 65,
    phone: 593,
    icon: require('./country_assets/EC.png'),
  },
  {
    name: 'Egypt',
    code: 'EG',
    id: 66,
    phone: 20,
    icon: require('./country_assets/EG.png'),
  },
  {
    name: 'El Salvador',
    code: 'SV',
    id: 67,
    phone: 503,
    icon: require('./country_assets/SV.png'),
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    id: 68,
    phone: 240,
    icon: require('./country_assets/GQ.png'),
  },
  {
    name: 'Eritrea',
    code: 'ER',
    id: 69,
    phone: 291,
    icon: require('./country_assets/ER.png'),
  },
  {
    name: 'Estonia',
    code: 'EE',
    id: 70,
    phone: 372,
    icon: require('./country_assets/EE.png'),
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    id: 71,
    phone: 251,
    icon: require('./country_assets/ET.png'),
  },
  {
    name: 'Falkland Islands (Malvinas)',
    code: 'FK',
    id: 72,
    phone: 500,
    icon: require('./country_assets/FK.png'),
  },
  {
    name: 'Faroe Islands',
    code: 'FO',
    id: 73,
    phone: 298,
    icon: require('./country_assets/FO.png'),
  },
  {
    name: 'Fiji',
    code: 'FJ',
    id: 74,
    phone: 679,
    icon: require('./country_assets/FJ.png'),
  },
  {
    name: 'Finland',
    code: 'FI',
    id: 75,
    phone: 358,
    icon: require('./country_assets/FI.png'),
  },
  {
    name: 'France',
    code: 'FR',
    id: 76,
    phone: 33,
    icon: require('./country_assets/FR.png'),
  },
  {
    name: 'French Guiana',
    code: 'GF',
    id: 77,
    phone: 594,
    icon: require('./country_assets/GF.png'),
  },
  {
    name: 'French Polynesia',
    code: 'PF',
    id: 78,
    phone: 689,
    icon: require('./country_assets/PF.png'),
  },
  {
    name: 'French Southern Territories',
    code: 'TF',
    id: 79,
    phone: 262,
    icon: require('./country_assets/TF.png'),
  },
  {
    name: 'Gabon',
    code: 'GA',
    id: 80,
    phone: 241,
    icon: require('./country_assets/GA.png'),
  },
  {
    name: 'Gambia',
    code: 'GM',
    id: 81,
    phone: 220,
    icon: require('./country_assets/GM.png'),
  },
  {
    name: 'Georgia',
    code: 'GE',
    id: 82,
    phone: 995,
    icon: require('./country_assets/GE.png'),
  },
  {
    name: 'Germany',
    code: 'DE',
    id: 83,
    phone: 49,
    icon: require('./country_assets/DE.png'),
  },
  {
    name: 'Ghana',
    code: 'GH',
    id: 84,
    phone: 233,
    icon: require('./country_assets/GH.png'),
  },
  {
    name: 'Gibraltar',
    code: 'GI',
    id: 85,
    phone: 350,
    icon: require('./country_assets/GI.png'),
  },
  {
    name: 'Greece',
    code: 'GR',
    id: 86,
    phone: 30,
    icon: require('./country_assets/GR.png'),
  },
  {
    name: 'Greenland',
    code: 'GL',
    id: 87,
    phone: 299,
    icon: require('./country_assets/GL.png'),
  },
  {
    name: 'Grenada',
    code: 'GD',
    id: 88,
    phone: 1473,
    icon: require('./country_assets/GD.png'),
  },
  {
    name: 'Guadeloupe',
    code: 'GP',
    id: 89,
    phone: 590,
    icon: require('./country_assets/GP.png'),
  },
  {
    name: 'Guam',
    code: 'GU',
    id: 90,
    phone: 1671,
    icon: require('./country_assets/GU.png'),
  },
  {
    name: 'Guatemala',
    code: 'GT',
    id: 91,
    phone: 502,
    icon: require('./country_assets/GT.png'),
  },
  {
    name: 'Guernsey',
    code: 'GG',
    id: 92,
    phone: 44,
    icon: require('./country_assets/GG.png'),
  },
  {
    name: 'Guinea',
    code: 'GN',
    id: 93,
    phone: 224,
    icon: require('./country_assets/GN.png'),
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    id: 94,
    phone: 245,
    icon: require('./country_assets/GW.png'),
  },
  {
    name: 'Guyana',
    code: 'GY',
    id: 95,
    phone: 592,
    icon: require('./country_assets/GY.png'),
  },
  {
    name: 'Haiti',
    code: 'HT',
    id: 96,
    phone: 509,
    icon: require('./country_assets/HT.png'),
  },
  {
    name: 'Heard Island and Mcdonald Islands',
    code: 'HM',
    id: 97,
    phone: 0,
    icon: require('./country_assets/HM.png'),
  },
  {
    name: 'Holy See (Vatican City State)',
    code: 'VA',
    id: 98,
    phone: 39,
    icon: require('./country_assets/VA.png'),
  },
  {
    name: 'Honduras',
    code: 'HN',
    id: 99,
    phone: 504,
    icon: require('./country_assets/HN.png'),
  },
  {
    name: 'Hong Kong',
    code: 'HK',
    id: 100,
    phone: 852,
    icon: require('./country_assets/HK.png'),
  },
  {
    name: 'Hungary',
    code: 'HU',
    id: 101,
    phone: 36,
    icon: require('./country_assets/HU.png'),
  },
  {
    name: 'Iceland',
    code: 'IS',
    id: 102,
    phone: 354,
    icon: require('./country_assets/IS.png'),
  },
  {
    name: 'India',
    code: 'IN',
    id: 103,
    phone: 91,
    icon: require('./country_assets/IN.png'),
  },
  {
    name: 'Indonesia',
    code: 'ID',
    id: 104,
    phone: 62,
    icon: require('./country_assets/ID.png'),
  },
  {
    name: 'Iran, Islamic Republic of',
    code: 'IR',
    id: 105,
    phone: 98,
    icon: require('./country_assets/IR.png'),
  },
  {
    name: 'Iraq',
    code: 'IQ',
    id: 106,
    phone: 964,
    icon: require('./country_assets/IQ.png'),
  },
  {
    name: 'Ireland',
    code: 'IE',
    id: 107,
    phone: 353,
    icon: require('./country_assets/IE.png'),
  },
  {
    name: 'Isle of Man',
    code: 'IM',
    id: 108,
    phone: 44,
    icon: require('./country_assets/IM.png'),
  },
  {
    name: 'Israel',
    code: 'IL',
    id: 109,
    phone: 972,
    icon: require('./country_assets/IL.png'),
  },
  {
    name: 'Italy',
    code: 'IT',
    id: 110,
    phone: 39,
    icon: require('./country_assets/IT.png'),
  },
  {
    name: 'Jamaica',
    code: 'JM',
    id: 111,
    phone: 1876,
    icon: require('./country_assets/JM.png'),
  },
  {
    name: 'Japan',
    code: 'JP',
    id: 112,
    phone: 81,
    icon: require('./country_assets/JP.png'),
  },
  {
    name: 'Jersey',
    code: 'JE',
    id: 113,
    phone: 44,
    icon: require('./country_assets/JE.png'),
  },
  {
    name: 'Jordan',
    code: 'JO',
    id: 114,
    phone: 962,
    icon: require('./country_assets/JO.png'),
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    id: 115,
    phone: 7,
    icon: require('./country_assets/KZ.png'),
  },
  {
    name: 'Kenya',
    code: 'KE',
    id: 116,
    phone: 254,
    icon: require('./country_assets/KE.png'),
  },
  {
    name: 'Kiribati',
    code: 'KI',
    id: 117,
    phone: 686,
    icon: require('./country_assets/KI.png'),
  },
  {
    name: "Korea, Democratic People's Republic of",
    code: 'KP',
    id: 118,
    phone: 850,
    icon: require('./country_assets/KP.png'),
  },
  {
    name: 'Korea, Republic of',
    code: 'KR',
    id: 119,
    phone: 82,
    icon: require('./country_assets/KR.png'),
  },
  {
    name: 'Kosovo',
    code: 'XK',
    id: 120,
    phone: 381,
    icon: require('./country_assets/XK.png'),
  },
  {
    name: 'Kuwait',
    code: 'KW',
    id: 121,
    phone: 965,
    icon: require('./country_assets/KW.png'),
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    id: 122,
    phone: 996,
    icon: require('./country_assets/KG.png'),
  },
  {
    name: "Lao People's Democratic Republic",
    code: 'LA',
    id: 123,
    phone: 856,
    icon: require('./country_assets/LA.png'),
  },
  {
    name: 'Latvia',
    code: 'LV',
    id: 124,
    phone: 371,
    icon: require('./country_assets/LV.png'),
  },
  {
    name: 'Lebanon',
    code: 'LB',
    id: 125,
    phone: 961,
    icon: require('./country_assets/LB.png'),
  },
  {
    name: 'Lesotho',
    code: 'LS',
    id: 126,
    phone: 266,
    icon: require('./country_assets/LS.png'),
  },
  {
    name: 'Liberia',
    code: 'LR',
    id: 127,
    phone: 231,
    icon: require('./country_assets/LR.png'),
  },
  {
    name: 'Libyan Arab Jamahiriya',
    code: 'LY',
    id: 128,
    phone: 218,
    icon: require('./country_assets/LY.png'),
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    id: 129,
    phone: 423,
    icon: require('./country_assets/LI.png'),
  },
  {
    name: 'Lithuania',
    code: 'LT',
    id: 130,
    phone: 370,
    icon: require('./country_assets/LT.png'),
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    id: 131,
    phone: 352,
    icon: require('./country_assets/LU.png'),
  },
  {
    name: 'Macao',
    code: 'MO',
    id: 132,
    phone: 853,
    icon: require('./country_assets/MO.png'),
  },
  {
    name: 'Macedonia, the Former Yugoslav Republic of',
    code: 'MK',
    id: 133,
    phone: 389,
    icon: require('./country_assets/MK.png'),
  },
  {
    name: 'Madagascar',
    code: 'MG',
    id: 134,
    phone: 261,
    icon: require('./country_assets/MG.png'),
  },
  {
    name: 'Malawi',
    code: 'MW',
    id: 135,
    phone: 265,
    icon: require('./country_assets/MW.png'),
  },
  {
    name: 'Malaysia',
    code: 'MY',
    id: 136,
    phone: 60,
    icon: require('./country_assets/MY.png'),
  },
  {
    name: 'Maldives',
    code: 'MV',
    id: 137,
    phone: 960,
    icon: require('./country_assets/MV.png'),
  },
  {
    name: 'Mali',
    code: 'ML',
    id: 138,
    phone: 223,
    icon: require('./country_assets/ML.png'),
  },
  {
    name: 'Malta',
    code: 'MT',
    id: 139,
    phone: 356,
    icon: require('./country_assets/MT.png'),
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    id: 140,
    phone: 692,
    icon: require('./country_assets/MH.png'),
  },
  {
    name: 'Martinique',
    code: 'MQ',
    id: 141,
    phone: 596,
    icon: require('./country_assets/MQ.png'),
  },
  {
    name: 'Mauritania',
    code: 'MR',
    id: 142,
    phone: 222,
    icon: require('./country_assets/MR.png'),
  },
  {
    name: 'Mauritius',
    code: 'MU',
    id: 143,
    phone: 230,
    icon: require('./country_assets/MU.png'),
  },
  {
    name: 'Mayotte',
    code: 'YT',
    id: 144,
    phone: 269,
    icon: require('./country_assets/YT.png'),
  },
  {
    name: 'Mexico',
    code: 'MX',
    id: 145,
    phone: 52,
    icon: require('./country_assets/MX.png'),
  },
  {
    name: 'Micronesia, Federated States of',
    code: 'FM',
    id: 146,
    phone: 691,
    icon: require('./country_assets/FM.png'),
  },
  {
    name: 'Moldova, Republic of',
    code: 'MD',
    id: 147,
    phone: 373,
    icon: require('./country_assets/MD.png'),
  },
  {
    name: 'Monaco',
    code: 'MC',
    id: 148,
    phone: 377,
    icon: require('./country_assets/MC.png'),
  },
  {
    name: 'Mongolia',
    code: 'MN',
    id: 149,
    phone: 976,
    icon: require('./country_assets/MN.png'),
  },
  {
    name: 'Montenegro',
    code: 'ME',
    id: 150,
    phone: 382,
    icon: require('./country_assets/ME.png'),
  },
  {
    name: 'Montserrat',
    code: 'MS',
    id: 151,
    phone: 1664,
    icon: require('./country_assets/MS.png'),
  },
  {
    name: 'Morocco',
    code: 'MA',
    id: 152,
    phone: 212,
    icon: require('./country_assets/MA.png'),
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    id: 153,
    phone: 258,
    icon: require('./country_assets/MZ.png'),
  },
  {
    name: 'Myanmar',
    code: 'MM',
    id: 154,
    phone: 95,
    icon: require('./country_assets/MM.png'),
  },
  {
    name: 'Namibia',
    code: 'NA',
    id: 155,
    phone: 264,
    icon: require('./country_assets/NA.png'),
  },
  {
    name: 'Nauru',
    code: 'NR',
    id: 156,
    phone: 674,
    icon: require('./country_assets/NR.png'),
  },
  {
    name: 'Nepal',
    code: 'NP',
    id: 157,
    phone: 977,
    icon: require('./country_assets/NP.png'),
  },
  {
    name: 'Netherlands',
    code: 'NL',
    id: 158,
    phone: 31,
    icon: require('./country_assets/NL.png'),
  },
  {
    name: 'Netherlands Antilles',
    code: 'AN',
    id: 159,
    phone: 599,
    icon: require('./country_assets/AN.png'),
  },
  {
    name: 'New Caledonia',
    code: 'NC',
    id: 160,
    phone: 687,
    icon: require('./country_assets/NC.png'),
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    id: 161,
    phone: 64,
    icon: require('./country_assets/NZ.png'),
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    id: 162,
    phone: 505,
    icon: require('./country_assets/NI.png'),
  },
  {
    name: 'Niger',
    code: 'NE',
    id: 163,
    phone: 227,
    icon: require('./country_assets/NE.png'),
  },
  {
    name: 'Nigeria',
    code: 'NG',
    id: 164,
    phone: 234,
    icon: require('./country_assets/NG.png'),
  },
  {
    name: 'Niue',
    code: 'NU',
    id: 165,
    phone: 683,
    icon: require('./country_assets/NU.png'),
  },
  {
    name: 'Norfolk Island',
    code: 'NF',
    id: 166,
    phone: 672,
    icon: require('./country_assets/NF.png'),
  },
  {
    name: 'Northern Mariana Islands',
    code: 'MP',
    id: 167,
    phone: 1670,
    icon: require('./country_assets/MP.png'),
  },
  {
    name: 'Norway',
    code: 'NO',
    id: 168,
    phone: 47,
    icon: require('./country_assets/NO.png'),
  },
  {
    name: 'Oman',
    code: 'OM',
    id: 169,
    phone: 968,
    icon: require('./country_assets/OM.png'),
  },
  {
    name: 'Pakistan',
    code: 'PK',
    id: 170,
    phone: 92,
    icon: require('./country_assets/PK.png'),
  },
  {
    name: 'Palau',
    code: 'PW',
    id: 171,
    phone: 680,
    icon: require('./country_assets/PW.png'),
  },
  {
    name: 'Palestinian Territory, Occupied',
    code: 'PS',
    id: 172,
    phone: 970,
    icon: require('./country_assets/PS.png'),
  },
  {
    name: 'Panama',
    code: 'PA',
    id: 173,
    phone: 507,
    icon: require('./country_assets/PA.png'),
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    id: 174,
    phone: 675,
    icon: require('./country_assets/PG.png'),
  },
  {
    name: 'Paraguay',
    code: 'PY',
    id: 175,
    phone: 595,
    icon: require('./country_assets/PY.png'),
  },
  {
    name: 'Peru',
    code: 'PE',
    id: 176,
    phone: 51,
    icon: require('./country_assets/PE.png'),
  },
  {
    name: 'Philippines',
    code: 'PH',
    id: 177,
    phone: 63,
    icon: require('./country_assets/PH.png'),
  },
  {
    name: 'Pitcairn',
    code: 'PN',
    id: 178,
    phone: 64,
    icon: require('./country_assets/PN.png'),
  },
  {
    name: 'Poland',
    code: 'PL',
    id: 179,
    phone: 48,
    icon: require('./country_assets/PL.png'),
  },
  {
    name: 'Portugal',
    code: 'PT',
    id: 180,
    phone: 351,
    icon: require('./country_assets/PT.png'),
  },
  {
    name: 'Puerto Rico',
    code: 'PR',
    id: 181,
    phone: 1787,
    icon: require('./country_assets/PR.png'),
  },
  {
    name: 'Qatar',
    code: 'QA',
    id: 182,
    phone: 974,
    icon: require('./country_assets/QA.png'),
  },
  {
    name: 'Reunion',
    code: 'RE',
    id: 183,
    phone: 262,
    icon: require('./country_assets/RE.png'),
  },
  {
    name: 'Romania',
    code: 'RO',
    id: 184,
    phone: 40,
    icon: require('./country_assets/RO.png'),
  },
  {
    name: 'Russian Federation',
    code: 'RU',
    id: 185,
    phone: 70,
    icon: require('./country_assets/RU.png'),
  },
  {
    name: 'Rwanda',
    code: 'RW',
    id: 186,
    phone: 250,
    icon: require('./country_assets/RW.png'),
  },
  {
    name: 'Saint Barthelemy',
    code: 'BL',
    id: 187,
    phone: 590,
    icon: require('./country_assets/BL.png'),
  },
  {
    name: 'Saint Helena',
    code: 'SH',
    id: 188,
    phone: 290,
    icon: require('./country_assets/SH.png'),
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    id: 189,
    phone: 1869,
    icon: require('./country_assets/KN.png'),
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    id: 190,
    phone: 1758,
    icon: require('./country_assets/LC.png'),
  },
  {
    name: 'Saint Martin',
    code: 'MF',
    id: 191,
    phone: 590,
    icon: require('./country_assets/MF.png'),
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: 'PM',
    id: 192,
    phone: 508,
    icon: require('./country_assets/PM.png'),
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    id: 193,
    phone: 1784,
    icon: require('./country_assets/VC.png'),
  },
  {
    name: 'Samoa',
    code: 'WS',
    id: 194,
    phone: 684,
    icon: require('./country_assets/WS.png'),
  },
  {
    name: 'San Marino',
    code: 'SM',
    id: 195,
    phone: 378,
    icon: require('./country_assets/SM.png'),
  },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    id: 196,
    phone: 239,
    icon: require('./country_assets/ST.png'),
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    id: 197,
    phone: 966,
    icon: require('./country_assets/SA.png'),
  },
  {
    name: 'Senegal',
    code: 'SN',
    id: 198,
    phone: 221,
    icon: require('./country_assets/SN.png'),
  },
  {
    name: 'Serbia',
    code: 'RS',
    id: 199,
    phone: 381,
    icon: require('./country_assets/RS.png'),
  },
  {
    name: 'Serbia and Montenegro',
    code: 'CS',
    id: 200,
    phone: 381,
    icon: require('./country_assets/CS.png'),
  },
  {
    name: 'Seychelles',
    code: 'SC',
    id: 201,
    phone: 248,
    icon: require('./country_assets/SC.png'),
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    id: 202,
    phone: 232,
    icon: require('./country_assets/SL.png'),
  },
  {
    name: 'Singapore',
    code: 'SG',
    id: 203,
    phone: 65,
    icon: require('./country_assets/SG.png'),
  },
  {
    name: 'Sint Maarten',
    code: 'SX',
    id: 204,
    phone: 1,
    icon: require('./country_assets/SX.png'),
  },
  {
    name: 'Slovakia',
    code: 'SK',
    id: 205,
    phone: 421,
    icon: require('./country_assets/SK.png'),
  },
  {
    name: 'Slovenia',
    code: 'SI',
    id: 206,
    phone: 386,
    icon: require('./country_assets/SI.png'),
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    id: 207,
    phone: 677,
    icon: require('./country_assets/SB.png'),
  },
  {
    name: 'Somalia',
    code: 'SO',
    id: 208,
    phone: 252,
    icon: require('./country_assets/SO.png'),
  },
  {
    name: 'South Africa',
    code: 'ZA',
    id: 209,
    phone: 27,
    icon: require('./country_assets/ZA.png'),
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    id: 210,
    phone: 500,
    icon: require('./country_assets/GS.png'),
  },
  {
    name: 'South Sudan',
    code: 'SS',
    id: 211,
    phone: 211,
    icon: require('./country_assets/SS.png'),
  },
  {
    name: 'Spain',
    code: 'ES',
    id: 212,
    phone: 34,
    icon: require('./country_assets/ES.png'),
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    id: 213,
    phone: 94,
    icon: require('./country_assets/LK.png'),
  },
  {
    name: 'Sudan',
    code: 'SD',
    id: 214,
    phone: 249,
    icon: require('./country_assets/SD.png'),
  },
  {
    name: 'Suriname',
    code: 'SR',
    id: 215,
    phone: 597,
    icon: require('./country_assets/SR.png'),
  },
  {
    name: 'Svalbard and Jan Mayen',
    code: 'SJ',
    id: 216,
    phone: 47,
    icon: require('./country_assets/SJ.png'),
  },
  {
    name: 'Swaziland',
    code: 'SZ',
    id: 217,
    phone: 268,
    icon: require('./country_assets/SZ.png'),
  },
  {
    name: 'Sweden',
    code: 'SE',
    id: 218,
    phone: 46,
    icon: require('./country_assets/SE.png'),
  },
  {
    name: 'Switzerland',
    code: 'CH',
    id: 219,
    phone: 41,
    icon: require('./country_assets/CH.png'),
  },
  {
    name: 'Syrian Arab Republic',
    code: 'SY',
    id: 220,
    phone: 963,
    icon: require('./country_assets/SY.png'),
  },
  {
    name: 'Taiwan, Province of China',
    code: 'TW',
    id: 221,
    phone: 886,
    icon: require('./country_assets/TW.png'),
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    id: 222,
    phone: 992,
    icon: require('./country_assets/TJ.png'),
  },
  {
    name: 'Tanzania, United Republic of',
    code: 'TZ',
    id: 223,
    phone: 255,
    icon: require('./country_assets/TZ.png'),
  },
  {
    name: 'Thailand',
    code: 'TH',
    id: 224,
    phone: 66,
    icon: require('./country_assets/TH.png'),
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    id: 225,
    phone: 670,
    icon: require('./country_assets/TL.png'),
  },
  {
    name: 'Togo',
    code: 'TG',
    id: 226,
    phone: 228,
    icon: require('./country_assets/TG.png'),
  },
  {
    name: 'Tokelau',
    code: 'TK',
    id: 227,
    phone: 690,
    icon: require('./country_assets/TK.png'),
  },
  {
    name: 'Tonga',
    code: 'TO',
    id: 228,
    phone: 676,
    icon: require('./country_assets/TO.png'),
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    id: 229,
    phone: 1868,
    icon: require('./country_assets/TT.png'),
  },
  {
    name: 'Tunisia',
    code: 'TN',
    id: 230,
    phone: 216,
    icon: require('./country_assets/TN.png'),
  },
  {
    name: 'Turkey',
    code: 'TR',
    id: 231,
    phone: 90,
    icon: require('./country_assets/TR.png'),
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    id: 232,
    phone: 7370,
    icon: require('./country_assets/TM.png'),
  },
  {
    name: 'Turks and Caicos Islands',
    code: 'TC',
    id: 233,
    phone: 1649,
    icon: require('./country_assets/TC.png'),
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    id: 234,
    phone: 688,
    icon: require('./country_assets/TV.png'),
  },
  {
    name: 'Uganda',
    code: 'UG',
    id: 235,
    phone: 256,
    icon: require('./country_assets/UG.png'),
  },
  {
    name: 'Ukraine',
    code: 'UA',
    id: 236,
    phone: 380,
    icon: require('./country_assets/UA.png'),
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    id: 237,
    phone: 971,
    icon: require('./country_assets/AE.png'),
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    id: 238,
    phone: 44,
    icon: require('./country_assets/GB.png'),
  },
  {
    name: 'United States',
    code: 'US',
    id: 239,
    phone: 1,
    icon: require('./country_assets/US.png'),
  },
  {
    name: 'United States Minor Outlying Islands',
    code: 'UM',
    id: 240,
    phone: 1,
    icon: require('./country_assets/UM.png'),
  },
  {
    name: 'Uruguay',
    code: 'UY',
    id: 241,
    phone: 598,
    icon: require('./country_assets/UY.png'),
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    id: 242,
    phone: 998,
    icon: require('./country_assets/UZ.png'),
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    id: 243,
    phone: 678,
    icon: require('./country_assets/VU.png'),
  },
  {
    name: 'Venezuela',
    code: 'VE',
    id: 244,
    phone: 58,
    icon: require('./country_assets/VE.png'),
  },
  {
    name: 'Viet Nam',
    code: 'VN',
    id: 245,
    phone: 84,
    icon: require('./country_assets/VN.png'),
  },
  {
    name: 'Virgin Islands, British',
    code: 'VG',
    id: 246,
    phone: 1284,
    icon: require('./country_assets/VG.png'),
  },
  {
    name: 'Virgin Islands, U.s.',
    code: 'VI',
    id: 247,
    phone: 1340,
    icon: require('./country_assets/VI.png'),
  },
  {
    name: 'Wallis and Futuna',
    code: 'WF',
    id: 248,
    phone: 681,
    icon: require('./country_assets/WF.png'),
  },
  {
    name: 'Western Sahara',
    code: 'EH',
    id: 249,
    phone: 212,
    icon: require('./country_assets/EH.png'),
  },
  {
    name: 'Yemen',
    code: 'YE',
    id: 250,
    phone: 967,
    icon: require('./country_assets/YE.png'),
  },
  {
    name: 'Zambia',
    code: 'ZM',
    id: 251,
    phone: 260,
    icon: require('./country_assets/ZM.png'),
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    id: 252,
    phone: 263,
    icon: require('./country_assets/ZW.png'),
  },
];
