const Images = {
  boarding1: require('../assets/image/boarding1.png'),
  boarding2: require('../assets/image/boarding2.png'),
  boarding3: require('../assets/image/boarding3.png'),
  boarding4: require('../assets/image/boarding4.png'),
  con1: require('../assets/image/con1.png'),
  con2: require('../assets/image/con2.png'),
  con3: require('../assets/image/con3.png'),
  carrot: require('../assets/image/v_carrot.png'),
  corn: require('../assets/image/v_corn.png'),
  cucumber: require('../assets/image/v_cucumber.png'),
  potato: require('../assets/image/v_potato.png'),
  red_chili: require('../assets/image/v_red_chili_pepper.png'),
  tomato: require('../assets/image/v_tomato.png'),
  car1: require('../assets/image/car1.png'),
  car2: require('../assets/image/car2.png'),
  car3: require('../assets/image/car3.png'),
  car4: require('../assets/image/car4.png'),
  car5: require('../assets/image/car5.png'),
  car6: require('../assets/image/car6.png'),
  car7: require('../assets/image/car7.png'),
  car8: require('../assets/image/car8.png'),
  car9: require('../assets/image/car9.png'),
  onboarding21: require('../assets/image/onboarding21.png'),
  onboarding22: require('../assets/image/onboarding22.png'),
  onboarding23: require('../assets/image/onboarding23.png'),
  onboarding24: require('../assets/image/onboarding24.png'),
  onboarding25: require('../assets/image/onboarding25.png'),
};

export default Images;
